# -*- coding: utf-8 -*-
"""Task_3_Iris_Flower_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cy89APxfEUYdKzbLWpU0eakgwCwgbcg
"""

print("Hello, Data science!")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = load_iris()

# Convert it into a table (DataFrame)
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add the flower species column
df['species'] = iris.target

# Display the first 5 rows
df.head()

# Input features (measurements)
X = df.drop('species', axis=1)

# Output (flower species)
y = df['species']

print(X.head())
print(y.head())

# Split the dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", len(X_train))
print("Testing data:", len(X_test))

# Create the Decision Tree model
model = DecisionTreeClassifier()

# Train the model
model.fit(X_train, y_train)

print("Model trained successfully!")

# Predict the species for the test data
y_pred = model.predict(X_test)

print(y_pred)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

"""# Iris Flower Classification

### Name: Abhishek Singh Yadav

### CodeSoft Data Science Internship

### Task 3
"""

# Show the first 5 rows of the dataset
df.head()

# Create a graph of all features
df.hist(figsize=(10,8))
plt.show()

plt.scatter(df["sepal length (cm)"], df["petal length (cm)"])
plt.xlabel("Sepal Length (cm)")
plt.ylabel("Petal Length (cm)")
plt.title("Sepal Length vs Petal Length")
plt.show()

